### ISSUE TITLE
Query Params Get Duplicated in URL

### ISSUE THREAD

**Issue by polandj** [jorgegorka/svelte-router#33] opened 2020-01-24 18:46 UTC
Open any route, even if it doesn't do anything with query params.  Open it in your browser to the URL for that route and add ?a=b to the end of the URL.  Let it load.  The URL bar will now be: URL?a=b?a=b.  Hit reload, now it's URL?a=b?a=b?a=b?a=b.  It seems like somehow it's duplicating the entire query string.

Version info:
"svelte-router-spa": "^5.3.3",

**Comment by jorgegorka** [comment] 2020-02-16 17:55
Internally working with version 5.4.0 and can't reproduce the issue.  I'll publish 5.4 version in about two weeks.

**Comment by jorgegorka** [comment] 2020-03-02 08:18
Hey @polandj 

I'm going to close this issue since I can't reproduce it in version 5.4.2.

**Comment by vurpo** [comment] 2020-03-17 01:37
I'm having the exact same issue on version 5.4.3. I created a minimal demo app that reproduces it at https://github.com/vurpo/svelte-router-issue-33-demo . You should be able to just clone it, then `yarn install` and `yarn dev` (or the same with whatever package manager you want), and then open it in a browser and follow the steps above (up in the original issue). I tested in both Firefox and Chromium, both do the same thing.

**Comment by artecoop** [comment] 2020-03-19 16:11
Can confirm, I have the same problem: redirect and refresh keep adding query params

**Comment by jorgegorka** [comment] 2020-03-20 17:40
Fixed in version 5.4.4

Thank you very much @vurpo  for the repo. It's been very useful.

**Closed by jorgegorka** 2020-03-20 17:40 UTC
Labels: bug
